# Generated by Django 2.1.5 on 2019-01-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TibetToPinyin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tibet', models.CharField(max_length=10)),
                ('pinyin', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'TibetToPinyin',
                'verbose_name_plural': 'TibetToChineses',
            },
        ),
    ]
